name: Pharo Loading Targets

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
   loading-targets:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk:
          - Pharo64-10
          - Pharo64-11
        load-target:
          - development
          - dependent-sunit-extensions
          - deployment
          - tests
          - tools
    name: Load ${{ matrix.load-target }} - ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Load group in image
        run: smalltalkci -s ${{ matrix.smalltalk }} .smalltalkci/loading.${{ matrix.load-target }}.ston
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
